services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "15762:15672" # Giao diện quản trị RabbitMQ
      - "5672:5672"   # Port mặc định để các ứng dụng kết nối tới RabbitMQ
#      - "61613:61613"  # STOMP WebSocket
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices-network

  # MySQL cho User Service
  mysql-userdb:
    image: mysql:8.0
    container_name: mysql-userdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: userdb
    volumes:
      - ./mysql-userdb-data:/var/lib/mysql
    networks:
      - microservices-network

  # MySQL cho Course Service
  mysql-coursedb:
    image: mysql:8.0
    container_name: mysql-coursedb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: coursedb
    volumes:
      - ./mysql-coursedb-data:/var/lib/mysql
    networks:
      - microservices-network

  # MySQL cho Enroll Service
  mysql-enrolldb:
    image: mysql:8.0
    container_name: mysql-enrolldb
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: enrolldb
    volumes:
      - ./mysql-enrolldb-data:/var/lib/mysql
    networks:
      - microservices-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - mysql-userdb
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-userdb:3306/userdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    ports:
#      - 8081:8081
      - 50050:50050 # gRPC
    networks:
      - microservices-network

  course-service:
    build:
      context: ./course-service
    container_name: course-service
    depends_on:
      - mysql-coursedb
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-coursedb:3306/coursedb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    ports:
#      - 8082:8082
      - 50051:50051 # gRPC
    networks:
      - microservices-network

  payment-service:
    build:
      context: ./enroll-service
    container_name: payment-service
    depends_on:
      - mysql-enrolldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-enrolldb:3306/enrolldb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - PAYPAL_BASE_URL=https://api-m.sandbox.paypal.com
      - PAYPAL_CLIENT_ID=AU4Z15aMKmvo86Hxw2HWTcysTTVLykyhx1lyiYq52LA__4v3mLto55f4P97tuXNB4FvKOWv0EOfl4rYn
      - PAYPAL_SECRET=ED08WeNe4e6xJJnvAw6jcRTGs9M8s7VP0ziBKmFpzExzhKYaa2YrVVv7n3MMk8Y9p0_0EZGlEKjEJeBf
      - PAYPAL_CURRENCY=USD
      - PAYPAL_RETURN_URL=http://api-gateway:8080/api/payment/success
      - PAYPAL_CANCEL_URL=http://api-gateway:8080/api/payment/cancel
    ports:
      - 8083:8083
#      - 50052:50052 # gRPC
    networks:
      - microservices-network

  chat-service:
    build:
      context: ./chat-service
    container_name: chat-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://anhvh243:Kv9RzWTuamVcTlif@cluster0.xgxi5.mongodb.net/chatdb
#      - SPRING_RABBITMQ_HOST=rabbitmq
#      - SPRING_RABBITMQ_PORT=5672  # AMQP cho queue
#      - SPRING_RABBITMQ_STOMP_PORT=61613  # STOMP WebSocket
    ports:
      - 8084:8084
    networks:
      - microservices-network

  socket-service:
    build:
      context: ./socket-service
    container_name: socket-service
    environment:
      - MONGO_URI=mongodb+srv://anhvh243:Kv9RzWTuamVcTlif@cluster0.xgxi5.mongodb.net/chatdb
    ports:
      - 5001:5001
    networks:
      - microservices-network


  api-gateway:
    build:
      context: ./APIGateWay
    container_name: api-gateway
    depends_on:
      - user-service
      - course-service
      - payment-service
      - chat-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge
