server:
  port: 8080

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      forwarded:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
