syntax = "proto3";

package user;

option java_package = "com.example.payment";
option java_outer_classname = "PaymentRpcProto";

// Định nghĩa Payment Method
message PaymentMethod {
  int32 id = 1;
  int32 user_id = 2;
  string type = 3;
  string provider = 4;
  string account_number = 5;
  string expiration_date = 6;
  string created_at = 7;
}

// Request và Response
message GetPaymentMethodsRequest {
  int32 user_id = 1;
}

message GetPaymentMethodsResponse {
  repeated PaymentMethod methods = 1;
}

// Service
service PaymentService {
  rpc GetPaymentMethods(GetPaymentMethodsRequest) returns (GetPaymentMethodsResponse);
}
