spring:
  data:
    mongodb:
      uri: mongodb+srv://anhvh243:Kv9RzWTuamVcTlif@cluster0.xgxi5.mongodb.net/chatdb

server:
  port: 8084

#logging:
#  level:
#    org.springframework: DEBUG
