spring:
  main:
    web-application-type: none
  data:
    mongodb:
      uri: mongodb://root:rootpassword@localhost:27017/chatdb?authSource=admin


logging:
  level:
    org.springframework: DEBUG
